### ISSUE TITLE
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)

### ISSUE THREAD

**Issue by BMCLX0** [m1stadev/deleo#18]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/deleo/__main__.py", line 107, in main
    Restore(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/restore/restore.py", line 1258, in update
    self.recovery.boot_ramdisk()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/restore/recovery.py", line 473, in boot_ramdisk
    self.enter_restore()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/restore/recovery.py", line 371, in enter_restore
    self.send_applelogo()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/restore/recovery.py", line 274, in send_applelogo
    self.send_component(component)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/deleo/recovery.py", line 171, in send_component
    self.device.irecv.send_buffer(data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/irecv.py", line 169, in send_buffer
    n = self._device.write(0x04, chunk, timeout=USB_TIMEOUT)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/usb/core.py", line 113, in wrapper

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/usb/core.py", line 178, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/usb/backend/libusb1.py", line 829, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)

**Comment by BMCLX0** [comment]
The device is a black apple
